services:
  web:
    build: ./web
    ports:
      - "8080:8080"
    depends_on:
      - mongo
      - scheduler
      - worker
    networks:
      - app-net
    env_file:
      - .env
    environment:
      MONGO_URI: "mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/"
      DB_NAME: "ipa2026_db"
      INTERFACE_COLLECTION: "interface_status"

  scheduler:
    build: ./scheduler
    depends_on:
      - mongo
    networks:
      - app-net
    environment:
      MONGO_URI: "mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/"
      DB_NAME: "ipa2026_db"
      TARGET_QUEUE: "rabbitmq"
    env_file:
      - .env
  worker:
    build: ./worker
    depends_on:
      - mongo
      - rabbitmq
    networks:
      - app-net
    environment:
      MONGO_URI: "mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/"
      DB_NAME: "ipa2026_db"
      TARGET_QUEUE: "rabbitmq"
      INTERFACE_COLLECTION: "interface_status"
    env_file:
      - .env
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-net
    env_file:
      - .env

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-net
    env_file:
      - .env

volumes:
  mongo-data:

networks:
  app-net:
